spring:
  application:
    name: teabliss
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  security:
      oauth2:
        client:
          registration:
            google:
              client_id: ${GOOGLE_CLIENT_ID}
              client_secret: ${GOOGLE_CLIENT_SECRET}
              redirect-uri: https://{baseHost}{basePort}/login/oauth2/code/google
              scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
                - profile
                - email

mybatis:
  type-aliases-package: store.teabliss.**.entity
  type-handlers-package: store.taebliss.**.entity.typehandler
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

jwt:
  secret: ${JWT_SECRET}

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client_id: ${GOOGLE_CLIENT_ID}
#            client_secret: ${GOOGLE_CLIENT_SECRET}
#            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
#              - profile
#              - emailportone:
  beartoken: ${PORTONE_BEARTOKEN}