spring:
#  profiles:
#    active: oauth
  application:
    name: teabliss
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

mybatis:
  type-aliases-package: store.teabliss.**.entity
  type-handlers-package: store.taebliss.**.entity.typehandler
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

jwt:
  secret: teabliss_backend