name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.WAS_HOST }}
        username: ${{ secrets.WAS_USER }}
        key: ${{ secrets.WAS_SSH_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/BE_Tea_Bliss
          git pull https://github.com/Tea-Bliss/BE_Tea_Bliss.git
          cd ..
          docker compose down
          docker compose up -d
          
           
